apiVersion: v2
name: kube-prometheus-stack
description: kube-prometheus-stack Helm chart wrapper
type: application
version: 1.0.0
appVersion: "67.4.0"

dependencies:
  - name: kube-prometheus-stack
    version: "67.4.0"
    repository: https://prometheus-community.github.io/helm-charts
